### ISSUE TITLE
IT Design/Concept Ideas

### ISSUE THREAD

**Issue by cmuc24** [tarikcoskun/youtube-concept#1]
First of all, whow! I´ve seen a lot of YT-Clones but yes, you've created really the best one! 

I'm not a frontend designer and im pretty sure, u dont need another.
But i'll share some backend-, it-concept & design ideas, that could help considerations, decisions for further coding.

#### Three main usecases 
- YT Frontend alternatives 
- YT Video Collection Manager (local Storage) 
- YT Download Manager

There are a lot of "Frontend alternatives" and "Download Manager" out there, but only a few 'Video Collection' Manager. But 3in1, i've never seen. 

#### What kind of problems can be 'solved'?`
1. Where are coming videos and metadata from? Obtained by YT or maybe stored on your local disc? Both?
2. Do you like an 'alternative frontend' for browsing live data only? Or do you have a local video collection, managed or 'to be' managed?`Both?
3. Do you have a download manager that should compatible, or do you like to use one? 
 
Unfortunately, most of solutions are isolated by theyre own data model, even though the well known YT [API, data structure](https://developers.google.com/youtube/v3/docs/?apix=true) 
Secondly, contributions are difficult to be made, even if you are not familiar with NodeJS, AND VueJS, TypeScript, Python, JSON, Linting, Testing, Staging, Github, Docker, ElasticSearch, Redis, Express, Electron and so on.. By the way, documentation is not everyones friend.

IMHO, the main Challenge or 'Goal': an unified data model and separate code in maintanable microservices, modules.
1. separate Dataproviders (YT, local storage, User generated, Application related)
2. Extendable coding structure, support for plugins (i've seen already with VueJS )
3. app development first

Im writing down my thougts first time, collected after evaluation of nearly 60 repos. Thats only a small objective part, essence of. Lets chat if you are interested in further details and of course, Happy New Year / Yeni Yılın Kutlu Olsun
Tschüss

**Comment by tarikcoskun** [comment]
Hello and thanks for your amazing ideas :)

I haven't really thought of this project becoming a YouTube alternative, that's just a fun project I decided to make after seeing the concept designer Avdan's design. I was not planning to work on this project anymore, but I like your ideas and they might actually make this project into something that has a purpose to exist.

I'm not sure how we can handle all those YouTube stuff other than using APIs, which might not be the most efficient approach.
Currently I'm busy with school stuff, but we can think of it some other day. You can add me on discord if you have one: Tarık#0070, or you can suggest some other place, happy new year to you too!
